
package br.com.prefeitura.diadema.ws.abaco.hmg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsBuscaDadosBoletoTaxasDiversaSoapPort", targetNamespace = "AGATA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsBuscaDadosBoletoTaxasDiversaSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.prefeitura.diadema.ws.abaco.hmg.WsBuscaDadosBoletoTaxasDiversaExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "AGATAaction/AWSBUSCADADOSBOLETOTAXASDIVERSA.Execute")
    @WebResult(name = "wsBuscaDadosBoletoTaxasDiversa.ExecuteResponse", targetNamespace = "AGATA", partName = "parameters")
    public WsBuscaDadosBoletoTaxasDiversaExecuteResponse execute(
        @WebParam(name = "wsBuscaDadosBoletoTaxasDiversa.Execute", targetNamespace = "AGATA", partName = "parameters")
        WsBuscaDadosBoletoTaxasDiversaExecute parameters);

}
