
package br.com.prefeitura.diadema.ws.abaco.hmg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsBuscaDadosBoletoTaxasDiversa", targetNamespace = "AGATA", wsdlLocation = "http://aplics-teste.diadema.sp.gov.br:8080/agataoracle/servlet/awsbuscadadosboletotaxasdiversa?WSDL")
public class WsBuscaDadosBoletoTaxasDiversa
    extends Service
{

    private final static URL WSBUSCADADOSBOLETOTAXASDIVERSA_WSDL_LOCATION;
    private final static WebServiceException WSBUSCADADOSBOLETOTAXASDIVERSA_EXCEPTION;
    private final static QName WSBUSCADADOSBOLETOTAXASDIVERSA_QNAME = new QName("AGATA", "wsBuscaDadosBoletoTaxasDiversa");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://aplics-teste.diadema.sp.gov.br:8080/agataoracle/servlet/awsbuscadadosboletotaxasdiversa?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSBUSCADADOSBOLETOTAXASDIVERSA_WSDL_LOCATION = url;
        WSBUSCADADOSBOLETOTAXASDIVERSA_EXCEPTION = e;
    }

    public WsBuscaDadosBoletoTaxasDiversa() {
        super(__getWsdlLocation(), WSBUSCADADOSBOLETOTAXASDIVERSA_QNAME);
    }

    public WsBuscaDadosBoletoTaxasDiversa(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSBUSCADADOSBOLETOTAXASDIVERSA_QNAME, features);
    }

    public WsBuscaDadosBoletoTaxasDiversa(URL wsdlLocation) {
        super(wsdlLocation, WSBUSCADADOSBOLETOTAXASDIVERSA_QNAME);
    }

    public WsBuscaDadosBoletoTaxasDiversa(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSBUSCADADOSBOLETOTAXASDIVERSA_QNAME, features);
    }

    public WsBuscaDadosBoletoTaxasDiversa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsBuscaDadosBoletoTaxasDiversa(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsBuscaDadosBoletoTaxasDiversaSoapPort
     */
    @WebEndpoint(name = "wsBuscaDadosBoletoTaxasDiversaSoapPort")
    public WsBuscaDadosBoletoTaxasDiversaSoapPort getWsBuscaDadosBoletoTaxasDiversaSoapPort() {
        return super.getPort(new QName("AGATA", "wsBuscaDadosBoletoTaxasDiversaSoapPort"), WsBuscaDadosBoletoTaxasDiversaSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBuscaDadosBoletoTaxasDiversaSoapPort
     */
    @WebEndpoint(name = "wsBuscaDadosBoletoTaxasDiversaSoapPort")
    public WsBuscaDadosBoletoTaxasDiversaSoapPort getWsBuscaDadosBoletoTaxasDiversaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("AGATA", "wsBuscaDadosBoletoTaxasDiversaSoapPort"), WsBuscaDadosBoletoTaxasDiversaSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSBUSCADADOSBOLETOTAXASDIVERSA_EXCEPTION!= null) {
            throw WSBUSCADADOSBOLETOTAXASDIVERSA_EXCEPTION;
        }
        return WSBUSCADADOSBOLETOTAXASDIVERSA_WSDL_LOCATION;
    }

}
