
package br.com.prefeitura.diadema.ws.agiles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RolesServices", targetNamespace = "http://imagetechnology.com.br/agiles_services", wsdlLocation = "http://bpms-prod.diadema.sp.gov.br:8080/agiles-services/services/RolesServices?wsdl")
public class RolesServices_Service
    extends Service
{

    private final static URL ROLESSERVICES_WSDL_LOCATION;
    private final static WebServiceException ROLESSERVICES_EXCEPTION;
    private final static QName ROLESSERVICES_QNAME = new QName("http://imagetechnology.com.br/agiles_services", "RolesServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bpms-prod.diadema.sp.gov.br:8080/agiles-services/services/RolesServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROLESSERVICES_WSDL_LOCATION = url;
        ROLESSERVICES_EXCEPTION = e;
    }

    public RolesServices_Service() {
        super(__getWsdlLocation(), ROLESSERVICES_QNAME);
    }

    public RolesServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROLESSERVICES_QNAME, features);
    }

    public RolesServices_Service(URL wsdlLocation) {
        super(wsdlLocation, ROLESSERVICES_QNAME);
    }

    public RolesServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROLESSERVICES_QNAME, features);
    }

    public RolesServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RolesServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RolesServices
     */
    @WebEndpoint(name = "RolesServicesPort")
    public RolesServices getRolesServicesPort() {
        return super.getPort(new QName("http://imagetechnology.com.br/agiles_services", "RolesServicesPort"), RolesServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RolesServices
     */
    @WebEndpoint(name = "RolesServicesPort")
    public RolesServices getRolesServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imagetechnology.com.br/agiles_services", "RolesServicesPort"), RolesServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROLESSERVICES_EXCEPTION!= null) {
            throw ROLESSERVICES_EXCEPTION;
        }
        return ROLESSERVICES_WSDL_LOCATION;
    }

}
