
package br.com.prefeitura.diadema.ws.agiles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SingleSignOnServices", targetNamespace = "http://imagetechnology.com.br/agiles_services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SingleSignOnServices {


    /**
     * 
     * @param userLogin
     * @param ip
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoginToken", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.diadema.ws.agiles.GetLoginToken")
    @ResponseWrapper(localName = "getLoginTokenResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.diadema.ws.agiles.GetLoginTokenResponse")
    public String getLoginToken(
        @WebParam(name = "userLogin", targetNamespace = "")
        String userLogin,
        @WebParam(name = "ip", targetNamespace = "")
        String ip);

    /**
     * 
     * @param userLogin
     * @param password
     * @param ipAddress
     * @return
     *     returns br.com.diadema.ws.agiles.AgilesUser
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.diadema.ws.agiles.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.diadema.ws.agiles.LoginResponse")
    public AgilesUser login(
        @WebParam(name = "userLogin", targetNamespace = "")
        String userLogin,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "ipAddress", targetNamespace = "")
        String ipAddress);

    /**
     * 
     * @param ip
     * @param userKey
     * @return
     *     returns br.com.diadema.ws.agiles.AgilesUser
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoggedUser", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.diadema.ws.agiles.GetLoggedUser")
    @ResponseWrapper(localName = "getLoggedUserResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.diadema.ws.agiles.GetLoggedUserResponse")
    public AgilesUser getLoggedUser(
        @WebParam(name = "userKey", targetNamespace = "")
        String userKey,
        @WebParam(name = "ip", targetNamespace = "")
        String ip);

}
