
package br.com.prefeitura.diadema.ws.agiles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SingleSignOnServices", targetNamespace = "http://imagetechnology.com.br/agiles_services", wsdlLocation = "http://bpms-prod.diadema.sp.gov.br:8080/agiles-services/services/SingleSignOnServices?wsdl")
public class SingleSignOnServices_Service
    extends Service
{

    private final static URL SINGLESIGNONSERVICES_WSDL_LOCATION;
    private final static WebServiceException SINGLESIGNONSERVICES_EXCEPTION;
    private final static QName SINGLESIGNONSERVICES_QNAME = new QName("http://imagetechnology.com.br/agiles_services", "SingleSignOnServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bpms-prod.diadema.sp.gov.br:8080/agiles-services/services/SingleSignOnServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SINGLESIGNONSERVICES_WSDL_LOCATION = url;
        SINGLESIGNONSERVICES_EXCEPTION = e;
    }

    public SingleSignOnServices_Service() {
        super(__getWsdlLocation(), SINGLESIGNONSERVICES_QNAME);
    }

    public SingleSignOnServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SINGLESIGNONSERVICES_QNAME, features);
    }

    public SingleSignOnServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SINGLESIGNONSERVICES_QNAME);
    }

    public SingleSignOnServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SINGLESIGNONSERVICES_QNAME, features);
    }

    public SingleSignOnServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SingleSignOnServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SingleSignOnServices
     */
    @WebEndpoint(name = "SingleSignOnServicesPort")
    public SingleSignOnServices getSingleSignOnServicesPort() {
        return super.getPort(new QName("http://imagetechnology.com.br/agiles_services", "SingleSignOnServicesPort"), SingleSignOnServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SingleSignOnServices
     */
    @WebEndpoint(name = "SingleSignOnServicesPort")
    public SingleSignOnServices getSingleSignOnServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imagetechnology.com.br/agiles_services", "SingleSignOnServicesPort"), SingleSignOnServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SINGLESIGNONSERVICES_EXCEPTION!= null) {
            throw SINGLESIGNONSERVICES_EXCEPTION;
        }
        return SINGLESIGNONSERVICES_WSDL_LOCATION;
    }

}
