
package br.com.prefeitura.diadema.ws.agiles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UtilServices", targetNamespace = "http://imagetechnology.com.br/agiles_services", wsdlLocation = "http://bpms-prod.diadema.sp.gov.br:8080/agiles-services/services/UtilServices?wsdl")
public class UtilServices_Service
    extends Service
{

    private final static URL UTILSERVICES_WSDL_LOCATION;
    private final static WebServiceException UTILSERVICES_EXCEPTION;
    private final static QName UTILSERVICES_QNAME = new QName("http://imagetechnology.com.br/agiles_services", "UtilServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bpms-prod.diadema.sp.gov.br:8080/agiles-services/services/UtilServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UTILSERVICES_WSDL_LOCATION = url;
        UTILSERVICES_EXCEPTION = e;
    }

    public UtilServices_Service() {
        super(__getWsdlLocation(), UTILSERVICES_QNAME);
    }

    public UtilServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UTILSERVICES_QNAME, features);
    }

    public UtilServices_Service(URL wsdlLocation) {
        super(wsdlLocation, UTILSERVICES_QNAME);
    }

    public UtilServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UTILSERVICES_QNAME, features);
    }

    public UtilServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UtilServices
     */
    @WebEndpoint(name = "UtilServicesPort")
    public UtilServices getUtilServicesPort() {
        return super.getPort(new QName("http://imagetechnology.com.br/agiles_services", "UtilServicesPort"), UtilServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilServices
     */
    @WebEndpoint(name = "UtilServicesPort")
    public UtilServices getUtilServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imagetechnology.com.br/agiles_services", "UtilServicesPort"), UtilServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UTILSERVICES_EXCEPTION!= null) {
            throw UTILSERVICES_EXCEPTION;
        }
        return UTILSERVICES_WSDL_LOCATION;
    }

}
