
package br.com.prefeitura.diadema.ws.agiles;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtilServices", targetNamespace = "http://imagetechnology.com.br/agiles_services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtilServices {


    /**
     * 
     * @param itemPk
     * @param itemType
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findItemContainersByItemType", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.FindItemContainersByItemType")
    @ResponseWrapper(localName = "findItemContainersByItemTypeResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.FindItemContainersByItemTypeResponse")
    public List<String> findItemContainersByItemType(
        @WebParam(name = "itemPk", targetNamespace = "")
        String itemPk,
        @WebParam(name = "itemType", targetNamespace = "")
        String itemType);

    /**
     * 
     * @param itemPk
     * @param active
     */
    @WebMethod
    @RequestWrapper(localName = "setActive", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SetActive")
    @ResponseWrapper(localName = "setActiveResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SetActiveResponse")
    public void setActive(
        @WebParam(name = "itemPk", targetNamespace = "")
        String itemPk,
        @WebParam(name = "active", targetNamespace = "")
        boolean active);

    /**
     * 
     * @param cc
     * @param bcc
     * @param processPk
     * @param fromUserPk
     * @param subject
     * @param atachmentsPk
     * @param to
     * @param body
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmailForProcessWithAttachments", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SendEmailForProcessWithAttachments")
    @ResponseWrapper(localName = "sendEmailForProcessWithAttachmentsResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SendEmailForProcessWithAttachmentsResponse")
    public void sendEmailForProcessWithAttachments(
        @WebParam(name = "processPk", targetNamespace = "")
        String processPk,
        @WebParam(name = "fromUserPk", targetNamespace = "")
        String fromUserPk,
        @WebParam(name = "to", targetNamespace = "")
        String to,
        @WebParam(name = "cc", targetNamespace = "")
        String cc,
        @WebParam(name = "bcc", targetNamespace = "")
        String bcc,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "body", targetNamespace = "")
        String body,
        @WebParam(name = "atachmentsPk", targetNamespace = "")
        List<String> atachmentsPk);

    /**
     * 
     * @param cc
     * @param bcc
     * @param processPk
     * @param fromUserPk
     * @param subject
     * @param to
     * @param body
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmailForProcess", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SendEmailForProcess")
    @ResponseWrapper(localName = "sendEmailForProcessResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SendEmailForProcessResponse")
    public void sendEmailForProcess(
        @WebParam(name = "processPk", targetNamespace = "")
        String processPk,
        @WebParam(name = "fromUserPk", targetNamespace = "")
        String fromUserPk,
        @WebParam(name = "to", targetNamespace = "")
        String to,
        @WebParam(name = "cc", targetNamespace = "")
        String cc,
        @WebParam(name = "bcc", targetNamespace = "")
        String bcc,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "body", targetNamespace = "")
        String body);

    /**
     * 
     * @param itemPk
     * @return
     *     returns br.com.prefeitura.diadema.ws.agiles.AgilesItem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.GetItemResponse")
    public AgilesItem getItem(
        @WebParam(name = "itemPk", targetNamespace = "")
        String itemPk);

    /**
     * 
     * @param modified
     */
    @WebMethod
    @RequestWrapper(localName = "modifyUser", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.ModifyUser")
    @ResponseWrapper(localName = "modifyUserResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.ModifyUserResponse")
    public void modifyUser(
        @WebParam(name = "modified", targetNamespace = "")
        AgilesUser modified);

    /**
     * 
     * @param itemPk
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemName", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.GetItemName")
    @ResponseWrapper(localName = "getItemNameResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.GetItemNameResponse")
    public String getItemName(
        @WebParam(name = "itemPk", targetNamespace = "")
        String itemPk);

    /**
     * 
     * @param cc
     * @param variables
     * @param bcc
     * @param fromUserPk
     * @param subject
     * @param to
     * @param body
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SendEmailResponse")
    public void sendEmail(
        @WebParam(name = "variables", targetNamespace = "")
        HashMap variables,
        @WebParam(name = "fromUserPk", targetNamespace = "")
        String fromUserPk,
        @WebParam(name = "to", targetNamespace = "")
        String to,
        @WebParam(name = "cc", targetNamespace = "")
        String cc,
        @WebParam(name = "bcc", targetNamespace = "")
        String bcc,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "body", targetNamespace = "")
        String body);

    /**
     * 
     * @param result
     * @param performerIp
     * @param performedPkOn
     * @param action
     * @param message
     * @param performerPk
     */
    @WebMethod
    @RequestWrapper(localName = "createAuditTrail", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.CreateAuditTrail")
    @ResponseWrapper(localName = "createAuditTrailResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.CreateAuditTrailResponse")
    public void createAuditTrail(
        @WebParam(name = "action", targetNamespace = "")
        String action,
        @WebParam(name = "message", targetNamespace = "")
        String message,
        @WebParam(name = "performerPk", targetNamespace = "")
        String performerPk,
        @WebParam(name = "performerIp", targetNamespace = "")
        String performerIp,
        @WebParam(name = "performedPkOn", targetNamespace = "")
        String performedPkOn,
        @WebParam(name = "result", targetNamespace = "")
        String result);

    /**
     * 
     * @param itemPk
     * @param containerPk
     */
    @WebMethod
    @RequestWrapper(localName = "addToContainer", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.AddToContainer")
    @ResponseWrapper(localName = "addToContainerResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.AddToContainerResponse")
    public void addToContainer(
        @WebParam(name = "containerPk", targetNamespace = "")
        String containerPk,
        @WebParam(name = "itemPk", targetNamespace = "")
        String itemPk);

    /**
     * 
     * @param itemPk
     * @param principalPk
     * @param permissionName
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkPermission", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.CheckPermission")
    @ResponseWrapper(localName = "checkPermissionResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.CheckPermissionResponse")
    public boolean checkPermission(
        @WebParam(name = "principalPk", targetNamespace = "")
        String principalPk,
        @WebParam(name = "itemPk", targetNamespace = "")
        String itemPk,
        @WebParam(name = "permissionName", targetNamespace = "")
        String permissionName);

    /**
     * 
     * @param cc
     * @param variables
     * @param bcc
     * @param attachmentsPk
     * @param fromUserPk
     * @param subject
     * @param to
     * @param body
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmailWithAttachments", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SendEmailWithAttachments")
    @ResponseWrapper(localName = "sendEmailWithAttachmentsResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.SendEmailWithAttachmentsResponse")
    public void sendEmailWithAttachments(
        @WebParam(name = "variables", targetNamespace = "")
        HashMap variables,
        @WebParam(name = "fromUserPk", targetNamespace = "")
        String fromUserPk,
        @WebParam(name = "to", targetNamespace = "")
        String to,
        @WebParam(name = "cc", targetNamespace = "")
        String cc,
        @WebParam(name = "bcc", targetNamespace = "")
        String bcc,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "body", targetNamespace = "")
        String body,
        @WebParam(name = "attachmentsPk", targetNamespace = "")
        List<String> attachmentsPk);

    /**
     * 
     * @param modified
     */
    @WebMethod
    @RequestWrapper(localName = "modifyItem", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.ModifyItem")
    @ResponseWrapper(localName = "modifyItemResponse", targetNamespace = "http://imagetechnology.com.br/agiles_services", className = "br.com.prefeitura.diadema.ws.agiles.ModifyItemResponse")
    public void modifyItem(
        @WebParam(name = "modified", targetNamespace = "")
        AgilesItem modified);

}
