
package br.com.prefeitura.diadema.ws.abaco.hmg.inscricao;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsCadastroInscricaoMobiliario", targetNamespace = "AGATA", wsdlLocation =  UrlEndereco.EWSDL_URL + "agataoracle/servlet/awscadastroinscricaomobiliario?WSDL")
public class WsCadastroInscricaoMobiliario
    extends Service
{

    private final static URL WSCADASTROINSCRICAOMOBILIARIO_WSDL_LOCATION;
    private final static WebServiceException WSCADASTROINSCRICAOMOBILIARIO_EXCEPTION;
    private final static QName WSCADASTROINSCRICAOMOBILIARIO_QNAME = new QName("AGATA", "wsCadastroInscricaoMobiliario");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.EWSDL_URL + "agataoracle/servlet/awscadastroinscricaomobiliario?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCADASTROINSCRICAOMOBILIARIO_WSDL_LOCATION = url;
        WSCADASTROINSCRICAOMOBILIARIO_EXCEPTION = e;
    }

    public WsCadastroInscricaoMobiliario() {
        super(__getWsdlLocation(), WSCADASTROINSCRICAOMOBILIARIO_QNAME);
    }

    public WsCadastroInscricaoMobiliario(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCADASTROINSCRICAOMOBILIARIO_QNAME, features);
    }

    public WsCadastroInscricaoMobiliario(URL wsdlLocation) {
        super(wsdlLocation, WSCADASTROINSCRICAOMOBILIARIO_QNAME);
    }

    public WsCadastroInscricaoMobiliario(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCADASTROINSCRICAOMOBILIARIO_QNAME, features);
    }

    public WsCadastroInscricaoMobiliario(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsCadastroInscricaoMobiliario(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsCadastroInscricaoMobiliarioSoapPort
     */
    @WebEndpoint(name = "wsCadastroInscricaoMobiliarioSoapPort")
    public WsCadastroInscricaoMobiliarioSoapPort getWsCadastroInscricaoMobiliarioSoapPort() {
        return super.getPort(new QName("AGATA", "wsCadastroInscricaoMobiliarioSoapPort"), WsCadastroInscricaoMobiliarioSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsCadastroInscricaoMobiliarioSoapPort
     */
    @WebEndpoint(name = "wsCadastroInscricaoMobiliarioSoapPort")
    public WsCadastroInscricaoMobiliarioSoapPort getWsCadastroInscricaoMobiliarioSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("AGATA", "wsCadastroInscricaoMobiliarioSoapPort"), WsCadastroInscricaoMobiliarioSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCADASTROINSCRICAOMOBILIARIO_EXCEPTION!= null) {
            throw WSCADASTROINSCRICAOMOBILIARIO_EXCEPTION;
        }
        return WSCADASTROINSCRICAOMOBILIARIO_WSDL_LOCATION;
    }

}
