
package br.com.prefeitura.diadema.ws.abaco.hmg.inscricao;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsConsultarExistenciaDaEmpresa", targetNamespace = "AGATA", wsdlLocation = UrlEndereco.WSDL + "agataoracle/servlet/awsconsultarexistenciadaempresa?WSDL")
public class WsConsultarExistenciaDaEmpresa
    extends Service
{

    private final static URL WSCONSULTAREXISTENCIADAEMPRESA_WSDL_LOCATION;
    private final static WebServiceException WSCONSULTAREXISTENCIADAEMPRESA_EXCEPTION;
    private final static QName WSCONSULTAREXISTENCIADAEMPRESA_QNAME = new QName("AGATA", "wsConsultarExistenciaDaEmpresa");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.WSDL + "agataoracle/servlet/awsconsultarexistenciadaempresa?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONSULTAREXISTENCIADAEMPRESA_WSDL_LOCATION = url;
        WSCONSULTAREXISTENCIADAEMPRESA_EXCEPTION = e;
    }

    public WsConsultarExistenciaDaEmpresa() {
        super(__getWsdlLocation(), WSCONSULTAREXISTENCIADAEMPRESA_QNAME);
    }

    public WsConsultarExistenciaDaEmpresa(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONSULTAREXISTENCIADAEMPRESA_QNAME, features);
    }

    public WsConsultarExistenciaDaEmpresa(URL wsdlLocation) {
        super(wsdlLocation, WSCONSULTAREXISTENCIADAEMPRESA_QNAME);
    }

    public WsConsultarExistenciaDaEmpresa(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONSULTAREXISTENCIADAEMPRESA_QNAME, features);
    }

    public WsConsultarExistenciaDaEmpresa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsConsultarExistenciaDaEmpresa(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsConsultarExistenciaDaEmpresaSoapPort
     */
    @WebEndpoint(name = "wsConsultarExistenciaDaEmpresaSoapPort")
    public WsConsultarExistenciaDaEmpresaSoapPort getWsConsultarExistenciaDaEmpresaSoapPort() {
        return super.getPort(new QName("AGATA", "wsConsultarExistenciaDaEmpresaSoapPort"), WsConsultarExistenciaDaEmpresaSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsConsultarExistenciaDaEmpresaSoapPort
     */
    @WebEndpoint(name = "wsConsultarExistenciaDaEmpresaSoapPort")
    public WsConsultarExistenciaDaEmpresaSoapPort getWsConsultarExistenciaDaEmpresaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("AGATA", "wsConsultarExistenciaDaEmpresaSoapPort"), WsConsultarExistenciaDaEmpresaSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONSULTAREXISTENCIADAEMPRESA_EXCEPTION!= null) {
            throw WSCONSULTAREXISTENCIADAEMPRESA_EXCEPTION;
        }
        return WSCONSULTAREXISTENCIADAEMPRESA_WSDL_LOCATION;
    }

}
