
package br.com.prefeitura.diadema.ws.abaco.hmg.inscricao;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsConsultaExistenciaEmpresa", targetNamespace = "AGATA", wsdlLocation = UrlEndereco.EWSDL_URL + "agataoracle/servlet/awsconsultaexistenciaempresa?WSDL")
public class WsConsultaExistenciaEmpresa
    extends Service
{

    private final static URL WSCONSULTAEXISTENCIAEMPRESA_WSDL_LOCATION;
    private final static WebServiceException WSCONSULTAEXISTENCIAEMPRESA_EXCEPTION;
    private final static QName WSCONSULTAEXISTENCIAEMPRESA_QNAME = new QName("AGATA", "wsConsultaExistenciaEmpresa");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.EWSDL_URL + "agataoracle/servlet/awsconsultaexistenciaempresa?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONSULTAEXISTENCIAEMPRESA_WSDL_LOCATION = url;
        WSCONSULTAEXISTENCIAEMPRESA_EXCEPTION = e;
    }

    public WsConsultaExistenciaEmpresa() {
        super(__getWsdlLocation(), WSCONSULTAEXISTENCIAEMPRESA_QNAME);
    }

    public WsConsultaExistenciaEmpresa(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONSULTAEXISTENCIAEMPRESA_QNAME, features);
    }

    public WsConsultaExistenciaEmpresa(URL wsdlLocation) {
        super(wsdlLocation, WSCONSULTAEXISTENCIAEMPRESA_QNAME);
    }

    public WsConsultaExistenciaEmpresa(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONSULTAEXISTENCIAEMPRESA_QNAME, features);
    }

    public WsConsultaExistenciaEmpresa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsConsultaExistenciaEmpresa(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsConsultaExistenciaEmpresaSoapPort
     */
    @WebEndpoint(name = "wsConsultaExistenciaEmpresaSoapPort")
    public WsConsultaExistenciaEmpresaSoapPort getWsConsultaExistenciaEmpresaSoapPort() {
        return super.getPort(new QName("AGATA", "wsConsultaExistenciaEmpresaSoapPort"), WsConsultaExistenciaEmpresaSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsConsultaExistenciaEmpresaSoapPort
     */
    @WebEndpoint(name = "wsConsultaExistenciaEmpresaSoapPort")
    public WsConsultaExistenciaEmpresaSoapPort getWsConsultaExistenciaEmpresaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("AGATA", "wsConsultaExistenciaEmpresaSoapPort"), WsConsultaExistenciaEmpresaSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONSULTAEXISTENCIAEMPRESA_EXCEPTION!= null) {
            throw WSCONSULTAEXISTENCIAEMPRESA_EXCEPTION;
        }
        return WSCONSULTAEXISTENCIAEMPRESA_WSDL_LOCATION;
    }

}
