
package br.com.prefeitura.diadema.ws.abaco.hmg.inscricao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsConsultaExistenciaEmpresaSoapPort", targetNamespace = "AGATA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsConsultaExistenciaEmpresaSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.prefeitura.diadema.ws.abaco.hmg.inscricao.WsConsultaExistenciaEmpresaExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "AGATAaction/AWSCONSULTAEXISTENCIAEMPRESA.Execute")
    @WebResult(name = "wsConsultaExistenciaEmpresa.ExecuteResponse", targetNamespace = "AGATA", partName = "parameters")
    public WsConsultaExistenciaEmpresaExecuteResponse execute(
        @WebParam(name = "wsConsultaExistenciaEmpresa.Execute", targetNamespace = "AGATA", partName = "parameters")
        WsConsultaExistenciaEmpresaExecute parameters);

}
