
package br.com.prefeitura.diadema.ws.abaco.hmg.inscricao;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsVerificaInscricaoImobiliaria", targetNamespace = "AGATA", wsdlLocation = UrlEndereco.WSDL + "agataoracle/servlet/awsverificainscricaoimobiliaria?WSDL")
public class WsVerificaInscricaoImobiliaria
    extends Service
{

    private final static URL WSVERIFICAINSCRICAOIMOBILIARIA_WSDL_LOCATION;
    private final static WebServiceException WSVERIFICAINSCRICAOIMOBILIARIA_EXCEPTION;
    private final static QName WSVERIFICAINSCRICAOIMOBILIARIA_QNAME = new QName("AGATA", "wsVerificaInscricaoImobiliaria");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.WSDL + "agataoracle/servlet/awsverificainscricaoimobiliaria?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSVERIFICAINSCRICAOIMOBILIARIA_WSDL_LOCATION = url;
        WSVERIFICAINSCRICAOIMOBILIARIA_EXCEPTION = e;
    }

    public WsVerificaInscricaoImobiliaria() {
        super(__getWsdlLocation(), WSVERIFICAINSCRICAOIMOBILIARIA_QNAME);
    }

    public WsVerificaInscricaoImobiliaria(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSVERIFICAINSCRICAOIMOBILIARIA_QNAME, features);
    }

    public WsVerificaInscricaoImobiliaria(URL wsdlLocation) {
        super(wsdlLocation, WSVERIFICAINSCRICAOIMOBILIARIA_QNAME);
    }

    public WsVerificaInscricaoImobiliaria(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSVERIFICAINSCRICAOIMOBILIARIA_QNAME, features);
    }

    public WsVerificaInscricaoImobiliaria(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsVerificaInscricaoImobiliaria(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsVerificaInscricaoImobiliariaSoapPort
     */
    @WebEndpoint(name = "wsVerificaInscricaoImobiliariaSoapPort")
    public WsVerificaInscricaoImobiliariaSoapPort getWsVerificaInscricaoImobiliariaSoapPort() {
        return super.getPort(new QName("AGATA", "wsVerificaInscricaoImobiliariaSoapPort"), WsVerificaInscricaoImobiliariaSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsVerificaInscricaoImobiliariaSoapPort
     */
    @WebEndpoint(name = "wsVerificaInscricaoImobiliariaSoapPort")
    public WsVerificaInscricaoImobiliariaSoapPort getWsVerificaInscricaoImobiliariaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("AGATA", "wsVerificaInscricaoImobiliariaSoapPort"), WsVerificaInscricaoImobiliariaSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSVERIFICAINSCRICAOIMOBILIARIA_EXCEPTION!= null) {
            throw WSVERIFICAINSCRICAOIMOBILIARIA_EXCEPTION;
        }
        return WSVERIFICAINSCRICAOIMOBILIARIA_WSDL_LOCATION;
    }

}
