
package br.com.prefeitura.diadema.ws.egata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsBuscaMunicipioSoapPort", targetNamespace = "eAgata")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsBuscaMunicipioSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.WsBuscaMunicipioExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "eAgataaction/AWSBUSCAMUNICIPIO.Execute")
    @WebResult(name = "wsBuscaMunicipio.ExecuteResponse", targetNamespace = "eAgata", partName = "parameters")
    public WsBuscaMunicipioExecuteResponse execute(
        @WebParam(name = "wsBuscaMunicipio.Execute", targetNamespace = "eAgata", partName = "parameters")
        WsBuscaMunicipioExecute parameters);

}
