
package br.com.prefeitura.diadema.ws.egata;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsBuscaMunicipio", targetNamespace = "eAgata", wsdlLocation = UrlEndereco.EWSDL_URL + "awsbuscamunicipio?WSDL")
public class WsBuscaMunicipio
    extends Service
{

    private final static URL WSBUSCAMUNICIPIO_WSDL_LOCATION;
    private final static WebServiceException WSBUSCAMUNICIPIO_EXCEPTION;
    private final static QName WSBUSCAMUNICIPIO_QNAME = new QName("eAgata", "wsBuscaMunicipio");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.EWSDL_URL + "awsbuscamunicipio?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSBUSCAMUNICIPIO_WSDL_LOCATION = url;
        WSBUSCAMUNICIPIO_EXCEPTION = e;
    }

    public WsBuscaMunicipio() {
        super(__getWsdlLocation(), WSBUSCAMUNICIPIO_QNAME);
    }

    public WsBuscaMunicipio(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSBUSCAMUNICIPIO_QNAME, features);
    }

    public WsBuscaMunicipio(URL wsdlLocation) {
        super(wsdlLocation, WSBUSCAMUNICIPIO_QNAME);
    }

    public WsBuscaMunicipio(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSBUSCAMUNICIPIO_QNAME, features);
    }

    public WsBuscaMunicipio(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsBuscaMunicipio(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsBuscaMunicipioSoapPort
     */
    @WebEndpoint(name = "wsBuscaMunicipioSoapPort")
    public WsBuscaMunicipioSoapPort getWsBuscaMunicipioSoapPort() {
        return super.getPort(new QName("eAgata", "wsBuscaMunicipioSoapPort"), WsBuscaMunicipioSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBuscaMunicipioSoapPort
     */
    @WebEndpoint(name = "wsBuscaMunicipioSoapPort")
    public WsBuscaMunicipioSoapPort getWsBuscaMunicipioSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("eAgata", "wsBuscaMunicipioSoapPort"), WsBuscaMunicipioSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSBUSCAMUNICIPIO_EXCEPTION!= null) {
            throw WSBUSCAMUNICIPIO_EXCEPTION;
        }
        return WSBUSCAMUNICIPIO_WSDL_LOCATION;
    }

}
