
package br.com.prefeitura.diadema.ws.egata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsbuscabairrologradouro", targetNamespace = "eAgata", wsdlLocation = "http://hmg-abc.diadema.sp.gov.br/eagata/servlet/awsbuscabairrologradouro?WSDL")
public class Wsbuscabairrologradouro
    extends Service
{

    private final static URL WSBUSCABAIRROLOGRADOURO_WSDL_LOCATION;
    private final static WebServiceException WSBUSCABAIRROLOGRADOURO_EXCEPTION;
    private final static QName WSBUSCABAIRROLOGRADOURO_QNAME = new QName("eAgata", "wsbuscabairrologradouro");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://hmg-abc.diadema.sp.gov.br/eagata/servlet/awsbuscabairrologradouro?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSBUSCABAIRROLOGRADOURO_WSDL_LOCATION = url;
        WSBUSCABAIRROLOGRADOURO_EXCEPTION = e;
    }

    public Wsbuscabairrologradouro() {
        super(__getWsdlLocation(), WSBUSCABAIRROLOGRADOURO_QNAME);
    }

    public Wsbuscabairrologradouro(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSBUSCABAIRROLOGRADOURO_QNAME, features);
    }

    public Wsbuscabairrologradouro(URL wsdlLocation) {
        super(wsdlLocation, WSBUSCABAIRROLOGRADOURO_QNAME);
    }

    public Wsbuscabairrologradouro(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSBUSCABAIRROLOGRADOURO_QNAME, features);
    }

    public Wsbuscabairrologradouro(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wsbuscabairrologradouro(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsbuscabairrologradouroSoapPort
     */
    @WebEndpoint(name = "wsbuscabairrologradouroSoapPort")
    public WsbuscabairrologradouroSoapPort getWsbuscabairrologradouroSoapPort() {
        return super.getPort(new QName("eAgata", "wsbuscabairrologradouroSoapPort"), WsbuscabairrologradouroSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsbuscabairrologradouroSoapPort
     */
    @WebEndpoint(name = "wsbuscabairrologradouroSoapPort")
    public WsbuscabairrologradouroSoapPort getWsbuscabairrologradouroSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("eAgata", "wsbuscabairrologradouroSoapPort"), WsbuscabairrologradouroSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSBUSCABAIRROLOGRADOURO_EXCEPTION!= null) {
            throw WSBUSCABAIRROLOGRADOURO_EXCEPTION;
        }
        return WSBUSCABAIRROLOGRADOURO_WSDL_LOCATION;
    }

}
