
package br.com.prefeitura.diadema.ws.egata;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsBuscaDadosBoletoTaxasDiversas", targetNamespace = "eAgata", wsdlLocation = UrlEndereco.EWSDL_URL+ "awsbuscadadosboletotaxasdiversas?WSDL")
public class WsBuscaDadosBoletoTaxasDiversas
    extends Service
{

    private final static URL WSBUSCADADOSBOLETOTAXASDIVERSAS_WSDL_LOCATION;
    private final static WebServiceException WSBUSCADADOSBOLETOTAXASDIVERSAS_EXCEPTION;
    private final static QName WSBUSCADADOSBOLETOTAXASDIVERSAS_QNAME = new QName("eAgata", "wsBuscaDadosBoletoTaxasDiversas");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.EWSDL_URL+ "awsbuscadadosboletotaxasdiversas?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSBUSCADADOSBOLETOTAXASDIVERSAS_WSDL_LOCATION = url;
        WSBUSCADADOSBOLETOTAXASDIVERSAS_EXCEPTION = e;
    }

    public WsBuscaDadosBoletoTaxasDiversas() {
        super(__getWsdlLocation(), WSBUSCADADOSBOLETOTAXASDIVERSAS_QNAME);
    }

    public WsBuscaDadosBoletoTaxasDiversas(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSBUSCADADOSBOLETOTAXASDIVERSAS_QNAME, features);
    }

    public WsBuscaDadosBoletoTaxasDiversas(URL wsdlLocation) {
        super(wsdlLocation, WSBUSCADADOSBOLETOTAXASDIVERSAS_QNAME);
    }

    public WsBuscaDadosBoletoTaxasDiversas(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSBUSCADADOSBOLETOTAXASDIVERSAS_QNAME, features);
    }

    public WsBuscaDadosBoletoTaxasDiversas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsBuscaDadosBoletoTaxasDiversas(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsBuscaDadosBoletoTaxasDiversasSoapPort
     */
    @WebEndpoint(name = "wsBuscaDadosBoletoTaxasDiversasSoapPort")
    public WsBuscaDadosBoletoTaxasDiversasSoapPort getWsBuscaDadosBoletoTaxasDiversasSoapPort() {
        return super.getPort(new QName("eAgata", "wsBuscaDadosBoletoTaxasDiversasSoapPort"), WsBuscaDadosBoletoTaxasDiversasSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBuscaDadosBoletoTaxasDiversasSoapPort
     */
    @WebEndpoint(name = "wsBuscaDadosBoletoTaxasDiversasSoapPort")
    public WsBuscaDadosBoletoTaxasDiversasSoapPort getWsBuscaDadosBoletoTaxasDiversasSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("eAgata", "wsBuscaDadosBoletoTaxasDiversasSoapPort"), WsBuscaDadosBoletoTaxasDiversasSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSBUSCADADOSBOLETOTAXASDIVERSAS_EXCEPTION!= null) {
            throw WSBUSCADADOSBOLETOTAXASDIVERSAS_EXCEPTION;
        }
        return WSBUSCADADOSBOLETOTAXASDIVERSAS_WSDL_LOCATION;
    }

}
