
package br.com.prefeitura.diadema.ws.egata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCadastroInscricaoMobiliarioSoapPort", targetNamespace = "eAgata")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCadastroInscricaoMobiliarioSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.WSCadastroInscricaoMobiliarioExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "eAgataaction/AWSCADASTROINSCRICAOMOBILIARIO.Execute")
    @WebResult(name = "WSCadastroInscricaoMobiliario.ExecuteResponse", targetNamespace = "eAgata", partName = "parameters")
    public WSCadastroInscricaoMobiliarioExecuteResponse execute(
        @WebParam(name = "WSCadastroInscricaoMobiliario.Execute", targetNamespace = "eAgata", partName = "parameters")
        WSCadastroInscricaoMobiliarioExecute parameters);

}
