
package br.com.prefeitura.diadema.ws.egata;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsconsultaexistenciaempresa", targetNamespace = "eAgata", wsdlLocation = UrlEndereco.EWSDL_URL+ "awsconsultaexistenciaempresa?WSDL")
public class Wsconsultaexistenciaempresa
    extends Service
{

    private final static URL WSCONSULTAEXISTENCIAEMPRESA_WSDL_LOCATION;
    private final static WebServiceException WSCONSULTAEXISTENCIAEMPRESA_EXCEPTION;
    private final static QName WSCONSULTAEXISTENCIAEMPRESA_QNAME = new QName("eAgata", "wsconsultaexistenciaempresa");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.EWSDL_URL+ "awsconsultaexistenciaempresa?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONSULTAEXISTENCIAEMPRESA_WSDL_LOCATION = url;
        WSCONSULTAEXISTENCIAEMPRESA_EXCEPTION = e;
    }

    public Wsconsultaexistenciaempresa() {
        super(__getWsdlLocation(), WSCONSULTAEXISTENCIAEMPRESA_QNAME);
    }

    public Wsconsultaexistenciaempresa(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONSULTAEXISTENCIAEMPRESA_QNAME, features);
    }

    public Wsconsultaexistenciaempresa(URL wsdlLocation) {
        super(wsdlLocation, WSCONSULTAEXISTENCIAEMPRESA_QNAME);
    }

    public Wsconsultaexistenciaempresa(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONSULTAEXISTENCIAEMPRESA_QNAME, features);
    }

    public Wsconsultaexistenciaempresa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wsconsultaexistenciaempresa(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsconsultaexistenciaempresaSoapPort
     */
    @WebEndpoint(name = "wsconsultaexistenciaempresaSoapPort")
    public WsconsultaexistenciaempresaSoapPort getWsconsultaexistenciaempresaSoapPort() {
        return super.getPort(new QName("eAgata", "wsconsultaexistenciaempresaSoapPort"), WsconsultaexistenciaempresaSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsconsultaexistenciaempresaSoapPort
     */
    @WebEndpoint(name = "wsconsultaexistenciaempresaSoapPort")
    public WsconsultaexistenciaempresaSoapPort getWsconsultaexistenciaempresaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("eAgata", "wsconsultaexistenciaempresaSoapPort"), WsconsultaexistenciaempresaSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONSULTAEXISTENCIAEMPRESA_EXCEPTION!= null) {
            throw WSCONSULTAEXISTENCIAEMPRESA_EXCEPTION;
        }
        return WSCONSULTAEXISTENCIAEMPRESA_WSDL_LOCATION;
    }

}
