
package br.com.prefeitura.diadema.ws.egata;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSEnviarDadosEmpresa", targetNamespace = "eAgata", wsdlLocation = UrlEndereco.EWSDL_URL+ "awsenviardadosempresa?WSDL")
public class WSEnviarDadosEmpresa
    extends Service
{

    private final static URL WSENVIARDADOSEMPRESA_WSDL_LOCATION;
    private final static WebServiceException WSENVIARDADOSEMPRESA_EXCEPTION;
    private final static QName WSENVIARDADOSEMPRESA_QNAME = new QName("eAgata", "WSEnviarDadosEmpresa");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.EWSDL_URL+ "awsenviardadosempresa?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSENVIARDADOSEMPRESA_WSDL_LOCATION = url;
        WSENVIARDADOSEMPRESA_EXCEPTION = e;
    }

    public WSEnviarDadosEmpresa() {
        super(__getWsdlLocation(), WSENVIARDADOSEMPRESA_QNAME);
    }

    public WSEnviarDadosEmpresa(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSENVIARDADOSEMPRESA_QNAME, features);
    }

    public WSEnviarDadosEmpresa(URL wsdlLocation) {
        super(wsdlLocation, WSENVIARDADOSEMPRESA_QNAME);
    }

    public WSEnviarDadosEmpresa(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSENVIARDADOSEMPRESA_QNAME, features);
    }

    public WSEnviarDadosEmpresa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSEnviarDadosEmpresa(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSEnviarDadosEmpresaSoapPort
     */
    @WebEndpoint(name = "WSEnviarDadosEmpresaSoapPort")
    public WSEnviarDadosEmpresaSoapPort getWSEnviarDadosEmpresaSoapPort() {
        return super.getPort(new QName("eAgata", "WSEnviarDadosEmpresaSoapPort"), WSEnviarDadosEmpresaSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSEnviarDadosEmpresaSoapPort
     */
    @WebEndpoint(name = "WSEnviarDadosEmpresaSoapPort")
    public WSEnviarDadosEmpresaSoapPort getWSEnviarDadosEmpresaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("eAgata", "WSEnviarDadosEmpresaSoapPort"), WSEnviarDadosEmpresaSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSENVIARDADOSEMPRESA_EXCEPTION!= null) {
            throw WSENVIARDADOSEMPRESA_EXCEPTION;
        }
        return WSENVIARDADOSEMPRESA_WSDL_LOCATION;
    }

}
