
package br.com.prefeitura.diadema.ws.egata;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsEnderecamento", targetNamespace = "eAgata", wsdlLocation = UrlEndereco.EWSDL_URL+ "awsenderecamento?WSDL")
public class WsEnderecamento
    extends Service
{

    private final static URL WSENDERECAMENTO_WSDL_LOCATION;
    private final static WebServiceException WSENDERECAMENTO_EXCEPTION;
    private final static QName WSENDERECAMENTO_QNAME = new QName("eAgata", "wsEnderecamento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.EWSDL_URL+ "awsenderecamento?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSENDERECAMENTO_WSDL_LOCATION = url;
        WSENDERECAMENTO_EXCEPTION = e;
    }

    public WsEnderecamento() {
        super(__getWsdlLocation(), WSENDERECAMENTO_QNAME);
    }

    public WsEnderecamento(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSENDERECAMENTO_QNAME, features);
    }

    public WsEnderecamento(URL wsdlLocation) {
        super(wsdlLocation, WSENDERECAMENTO_QNAME);
    }

    public WsEnderecamento(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSENDERECAMENTO_QNAME, features);
    }

    public WsEnderecamento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsEnderecamento(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsEnderecamentoSoapPort
     */
    @WebEndpoint(name = "wsEnderecamentoSoapPort")
    public WsEnderecamentoSoapPort getWsEnderecamentoSoapPort() {
        return super.getPort(new QName("eAgata", "wsEnderecamentoSoapPort"), WsEnderecamentoSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsEnderecamentoSoapPort
     */
    @WebEndpoint(name = "wsEnderecamentoSoapPort")
    public WsEnderecamentoSoapPort getWsEnderecamentoSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("eAgata", "wsEnderecamentoSoapPort"), WsEnderecamentoSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSENDERECAMENTO_EXCEPTION!= null) {
            throw WSENDERECAMENTO_EXCEPTION;
        }
        return WSENDERECAMENTO_WSDL_LOCATION;
    }

}
