
package br.com.prefeitura.diadema.ws.egata;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsregistroboleto", targetNamespace = "eAgata", wsdlLocation =  UrlEndereco.EWSDL_URL+ "awsregistroboleto?WSDL")
public class Wsregistroboleto
    extends Service
{

    private final static URL WSREGISTROBOLETO_WSDL_LOCATION;
    private final static WebServiceException WSREGISTROBOLETO_EXCEPTION;
    private final static QName WSREGISTROBOLETO_QNAME = new QName("eAgata", "wsregistroboleto");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.EWSDL_URL+"awsregistroboleto?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSREGISTROBOLETO_WSDL_LOCATION = url;
        WSREGISTROBOLETO_EXCEPTION = e;
    }

    public Wsregistroboleto() {
        super(__getWsdlLocation(), WSREGISTROBOLETO_QNAME);
    }

    public Wsregistroboleto(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSREGISTROBOLETO_QNAME, features);
    }

    public Wsregistroboleto(URL wsdlLocation) {
        super(wsdlLocation, WSREGISTROBOLETO_QNAME);
    }

    public Wsregistroboleto(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSREGISTROBOLETO_QNAME, features);
    }

    public Wsregistroboleto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wsregistroboleto(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsregistroboletoSoapPort
     */
    @WebEndpoint(name = "wsregistroboletoSoapPort")
    public WsregistroboletoSoapPort getWsregistroboletoSoapPort() {
        return super.getPort(new QName("eAgata", "wsregistroboletoSoapPort"), WsregistroboletoSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsregistroboletoSoapPort
     */
    @WebEndpoint(name = "wsregistroboletoSoapPort")
    public WsregistroboletoSoapPort getWsregistroboletoSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("eAgata", "wsregistroboletoSoapPort"), WsregistroboletoSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSREGISTROBOLETO_EXCEPTION!= null) {
            throw WSREGISTROBOLETO_EXCEPTION;
        }
        return WSREGISTROBOLETO_WSDL_LOCATION;
    }

}
