
package br.com.prefeitura.diadema.ws.egata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsverificainscricaoimobiliaria", targetNamespace = "eAgata", wsdlLocation = "https://hmg-abc.diadema.sp.gov.br/eagata/servlet/awsverificainscricaoimobiliaria?WSDL")
public class Wsverificainscricaoimobiliaria
    extends Service
{

    private final static URL WSVERIFICAINSCRICAOIMOBILIARIA_WSDL_LOCATION;
    private final static WebServiceException WSVERIFICAINSCRICAOIMOBILIARIA_EXCEPTION;
    private final static QName WSVERIFICAINSCRICAOIMOBILIARIA_QNAME = new QName("eAgata", "wsverificainscricaoimobiliaria");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://hmg-abc.diadema.sp.gov.br/eagata/servlet/awsverificainscricaoimobiliaria?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSVERIFICAINSCRICAOIMOBILIARIA_WSDL_LOCATION = url;
        WSVERIFICAINSCRICAOIMOBILIARIA_EXCEPTION = e;
    }

    public Wsverificainscricaoimobiliaria() {
        super(__getWsdlLocation(), WSVERIFICAINSCRICAOIMOBILIARIA_QNAME);
    }

    public Wsverificainscricaoimobiliaria(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSVERIFICAINSCRICAOIMOBILIARIA_QNAME, features);
    }

    public Wsverificainscricaoimobiliaria(URL wsdlLocation) {
        super(wsdlLocation, WSVERIFICAINSCRICAOIMOBILIARIA_QNAME);
    }

    public Wsverificainscricaoimobiliaria(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSVERIFICAINSCRICAOIMOBILIARIA_QNAME, features);
    }

    public Wsverificainscricaoimobiliaria(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wsverificainscricaoimobiliaria(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsverificainscricaoimobiliariaSoapPort
     */
    @WebEndpoint(name = "wsverificainscricaoimobiliariaSoapPort")
    public WsverificainscricaoimobiliariaSoapPort getWsverificainscricaoimobiliariaSoapPort() {
        return super.getPort(new QName("eAgata", "wsverificainscricaoimobiliariaSoapPort"), WsverificainscricaoimobiliariaSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsverificainscricaoimobiliariaSoapPort
     */
    @WebEndpoint(name = "wsverificainscricaoimobiliariaSoapPort")
    public WsverificainscricaoimobiliariaSoapPort getWsverificainscricaoimobiliariaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("eAgata", "wsverificainscricaoimobiliariaSoapPort"), WsverificainscricaoimobiliariaSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSVERIFICAINSCRICAOIMOBILIARIA_EXCEPTION!= null) {
            throw WSVERIFICAINSCRICAOIMOBILIARIA_EXCEPTION;
        }
        return WSVERIFICAINSCRICAOIMOBILIARIA_WSDL_LOCATION;
    }

}
