
package br.com.prefeitura.diadema.ws.egata.execute;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "JucespFault", targetNamespace = "Jucesp.Services.Data/01")
public class ILicenciamentoListarSolicitacoesPorProtocoloREDESIMJucespFaultFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private JucespFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ILicenciamentoListarSolicitacoesPorProtocoloREDESIMJucespFaultFaultFaultMessage(String message, JucespFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ILicenciamentoListarSolicitacoesPorProtocoloREDESIMJucespFaultFaultFaultMessage(String message, JucespFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.prefeitura.diadema.ws.egata.execute.JucespFault
     */
    public JucespFault getFaultInfo() {
        return faultInfo;
    }

}
