
package br.com.prefeitura.diadema.ws.egata.execute;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILicenciamento", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILicenciamento {


    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.ListarSolicitacoesPorDataOut
     * @throws ILicenciamentoListarSolicitacoesPorDataJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ListarSolicitacoesPorData", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/ListarSolicitacoesPorData")
    @WebResult(name = "ListarSolicitacoesPorDataResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "ListarSolicitacoesPorData", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ListarSolicitacoesPorData")
    @ResponseWrapper(localName = "ListarSolicitacoesPorDataResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ListarSolicitacoesPorDataResponse")
    public ListarSolicitacoesPorDataOut listarSolicitacoesPorData(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        ListarSolicitacoesPorDataIn dto)
        throws ILicenciamentoListarSolicitacoesPorDataJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.ListarSolicitacoesPorCNJPOut
     * @throws ILicenciamentoListarSolicitacoesPorCNPJJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ListarSolicitacoesPorCNPJ", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/ListarSolicitacoesPorCNPJ")
    @WebResult(name = "ListarSolicitacoesPorCNPJResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "ListarSolicitacoesPorCNPJ", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ListarSolicitacoesPorCNPJ")
    @ResponseWrapper(localName = "ListarSolicitacoesPorCNPJResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ListarSolicitacoesPorCNPJResponse")
    public ListarSolicitacoesPorCNJPOut listarSolicitacoesPorCNPJ(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        ListarSolicitacoesPorCNJPIn dto)
        throws ILicenciamentoListarSolicitacoesPorCNPJJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.ListarSolicitacoesPorProtocoloREDESIMOut
     * @throws ILicenciamentoListarSolicitacoesPorProtocoloREDESIMJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ListarSolicitacoesPorProtocoloREDESIM", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/ListarSolicitacoesPorProtocoloREDESIM")
    @WebResult(name = "ListarSolicitacoesPorProtocoloREDESIMResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "ListarSolicitacoesPorProtocoloREDESIM", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ListarSolicitacoesPorProtocoloREDESIM")
    @ResponseWrapper(localName = "ListarSolicitacoesPorProtocoloREDESIMResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ListarSolicitacoesPorProtocoloREDESIMResponse")
    public ListarSolicitacoesPorProtocoloREDESIMOut listarSolicitacoesPorProtocoloREDESIM(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        ListarSolicitacoesPorProtocoloREDESIMIn dto)
        throws ILicenciamentoListarSolicitacoesPorProtocoloREDESIMJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.ConsultarDadosEmpresaOut
     * @throws ILicenciamentoConsultarDadosEmpresaJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarDadosEmpresa", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/ConsultarDadosEmpresa")
    @WebResult(name = "ConsultarDadosEmpresaResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "ConsultarDadosEmpresa", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ConsultarDadosEmpresa")
    @ResponseWrapper(localName = "ConsultarDadosEmpresaResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ConsultarDadosEmpresaResponse")
    public ConsultarDadosEmpresaOut consultarDadosEmpresa(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        ConsultarDadosEmpresaIn dto)
        throws ILicenciamentoConsultarDadosEmpresaJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.ConsultarSolicitacaoLicenciamentoOut
     * @throws ILicenciamentoConsultarSolicitacaoLicenciamentoJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarSolicitacaoLicenciamento", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/ConsultarSolicitacaoLicenciamento")
    @WebResult(name = "ConsultarSolicitacaoLicenciamentoResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "ConsultarSolicitacaoLicenciamento", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ConsultarSolicitacaoLicenciamento")
    @ResponseWrapper(localName = "ConsultarSolicitacaoLicenciamentoResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.ConsultarSolicitacaoLicenciamentoResponse")
    public ConsultarSolicitacaoLicenciamentoOut consultarSolicitacaoLicenciamento(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        ConsultarSolicitacaoLicenciamentoIn dto)
        throws ILicenciamentoConsultarSolicitacaoLicenciamentoJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.InformarInteracaoComOrgaoOut
     * @throws ILicenciamentoInformarInteracaoComOrgaoJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "InformarInteracaoComOrgao", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/InformarInteracaoComOrgao")
    @WebResult(name = "InformarInteracaoComOrgaoResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "InformarInteracaoComOrgao", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.InformarInteracaoComOrgao")
    @ResponseWrapper(localName = "InformarInteracaoComOrgaoResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.InformarInteracaoComOrgaoResponse")
    public InformarInteracaoComOrgaoOut informarInteracaoComOrgao(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        InformarInteracaoComOrgaoIn dto)
        throws ILicenciamentoInformarInteracaoComOrgaoJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.InformarConclusaoLicencaOut
     * @throws ILicenciamentoInformarConclusaoLicencaJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "InformarConclusaoLicenca", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/InformarConclusaoLicenca")
    @WebResult(name = "InformarConclusaoLicencaResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "InformarConclusaoLicenca", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.InformarConclusaoLicenca")
    @ResponseWrapper(localName = "InformarConclusaoLicencaResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.InformarConclusaoLicencaResponse")
    public InformarConclusaoLicencaOut informarConclusaoLicenca(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        InformarConclusaoLicencaIn dto)
        throws ILicenciamentoInformarConclusaoLicencaJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.CassarLicencaOut
     * @throws ILicenciamentoCassarLicencaJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CassarLicenca", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/CassarLicenca")
    @WebResult(name = "CassarLicencaResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "CassarLicenca", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.CassarLicenca")
    @ResponseWrapper(localName = "CassarLicencaResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.CassarLicencaResponse")
    public CassarLicencaOut cassarLicenca(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        CassarLicencaIn dto)
        throws ILicenciamentoCassarLicencaJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.InvalidarLicencaOut
     * @throws ILicenciamentoInvalidarLicencaJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "InvalidarLicenca", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/InvalidarLicenca")
    @WebResult(name = "InvalidarLicencaResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "InvalidarLicenca", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.InvalidarLicenca")
    @ResponseWrapper(localName = "InvalidarLicencaResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.InvalidarLicencaResponse")
    public InvalidarLicencaOut invalidarLicenca(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        InvalidarLicencaIn dto)
        throws ILicenciamentoInvalidarLicencaJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.CancelarCassarLicencaOut
     * @throws ILicenciamentoCancelarCassarLicencaJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CancelarCassarLicenca", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/CancelarCassarLicenca")
    @WebResult(name = "CancelarCassarLicencaResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "CancelarCassarLicenca", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.CancelarCassarLicenca")
    @ResponseWrapper(localName = "CancelarCassarLicencaResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.CancelarCassarLicencaResponse")
    public CancelarCassarLicencaOut cancelarCassarLicenca(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        CancelarCassarLicencaIn dto)
        throws ILicenciamentoCancelarCassarLicencaJucespFaultFaultFaultMessage
    ;

    /**
     * 
     * @param dto
     * @return
     *     returns br.com.prefeitura.diadema.ws.egata.execute.LiberarCassarLicencaOut
     * @throws ILicenciamentoLiberarCassarLicencaJucespFaultFaultFaultMessage
     */
    @WebMethod(operationName = "LiberarCassarLicenca", action = "Jucesp.Services.Licenciamentos.Licenciamento/ILicenciamento/LiberarCassarLicenca")
    @WebResult(name = "LiberarCassarLicencaResult", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
    @RequestWrapper(localName = "LiberarCassarLicenca", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.LiberarCassarLicenca")
    @ResponseWrapper(localName = "LiberarCassarLicencaResponse", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", className = "br.com.prefeitura.diadema.ws.egata.execute.LiberarCassarLicencaResponse")
    public LiberarCassarLicencaOut liberarCassarLicenca(
        @WebParam(name = "dto", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento")
        LiberarCassarLicencaIn dto)
        throws ILicenciamentoLiberarCassarLicencaJucespFaultFaultFaultMessage
    ;

}
