
package br.com.prefeitura.diadema.ws.egata.execute;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Licenciamento", targetNamespace = "Jucesp.Services.Licenciamentos.Licenciamento", wsdlLocation = "https://www.jucesp.sp.gov.br/Jucesp.Services/Licenciamentos/Licenciamento.svc?wsdl")
public class Licenciamento
    extends Service
{

    private final static URL LICENCIAMENTO_WSDL_LOCATION;
    private final static WebServiceException LICENCIAMENTO_EXCEPTION;
    private final static QName LICENCIAMENTO_QNAME = new QName("Jucesp.Services.Licenciamentos.Licenciamento", "Licenciamento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.jucesp.sp.gov.br/Jucesp.Services/Licenciamentos/Licenciamento.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LICENCIAMENTO_WSDL_LOCATION = url;
        LICENCIAMENTO_EXCEPTION = e;
    }

    public Licenciamento() {
        super(__getWsdlLocation(), LICENCIAMENTO_QNAME);
    }

    public Licenciamento(WebServiceFeature... features) {
        super(__getWsdlLocation(), LICENCIAMENTO_QNAME, features);
    }

    public Licenciamento(URL wsdlLocation) {
        super(wsdlLocation, LICENCIAMENTO_QNAME);
    }

    public Licenciamento(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LICENCIAMENTO_QNAME, features);
    }

    public Licenciamento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Licenciamento(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ILicenciamento
     */
    @WebEndpoint(name = "Jucesp_BasicHttpBinding")
    public ILicenciamento getJucespBasicHttpBinding() {
        return super.getPort(new QName("Jucesp.Services.Licenciamentos.Licenciamento", "Jucesp_BasicHttpBinding"), ILicenciamento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILicenciamento
     */
    @WebEndpoint(name = "Jucesp_BasicHttpBinding")
    public ILicenciamento getJucespBasicHttpBinding(WebServiceFeature... features) {
        return super.getPort(new QName("Jucesp.Services.Licenciamentos.Licenciamento", "Jucesp_BasicHttpBinding"), ILicenciamento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LICENCIAMENTO_EXCEPTION!= null) {
            throw LICENCIAMENTO_EXCEPTION;
        }
        return LICENCIAMENTO_WSDL_LOCATION;
    }

}
