
package br.com.prefeitura.diadema.ws.abaco.hmg.enviar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsEnviarDadosEmpresaSoapPort", targetNamespace = "AGATA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsEnviarDadosEmpresaSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.prefeitura.diadema.ws.abaco.hmg.inscricao.WsEnviarDadosEmpresaExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "AGATAaction/AWSENVIARDADOSEMPRESA.Execute")
    @WebResult(name = "wsEnviarDadosEmpresa.ExecuteResponse", targetNamespace = "AGATA", partName = "parameters")
    public WsEnviarDadosEmpresaExecuteResponse execute(
        @WebParam(name = "wsEnviarDadosEmpresa.Execute", targetNamespace = "AGATA", partName = "parameters")
        WsEnviarDadosEmpresaExecute parameters);

}
