
package br.com.prefeitura.diadema.ws.abaco.hmg.lancar;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.prefeitura.diadema.util.UrlEndereco;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsLancarTaxasDiversas", targetNamespace = "AGATA", wsdlLocation = UrlEndereco.EWSDL_URL + "agataoracle/servletawslancartaxasdiversas?WSDL")
public class WsLancarTaxasDiversas
    extends Service
{

    private final static URL WSLANCARTAXASDIVERSAS_WSDL_LOCATION;
    private final static WebServiceException WSLANCARTAXASDIVERSAS_EXCEPTION;
    private final static QName WSLANCARTAXASDIVERSAS_QNAME = new QName("AGATA", "wsLancarTaxasDiversas");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(UrlEndereco.EWSDL_URL + "agataoracle/servlet/awslancartaxasdiversas?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSLANCARTAXASDIVERSAS_WSDL_LOCATION = url;
        WSLANCARTAXASDIVERSAS_EXCEPTION = e;
    }

    public WsLancarTaxasDiversas() {
        super(__getWsdlLocation(), WSLANCARTAXASDIVERSAS_QNAME);
    }

    public WsLancarTaxasDiversas(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSLANCARTAXASDIVERSAS_QNAME, features);
    }

    public WsLancarTaxasDiversas(URL wsdlLocation) {
        super(wsdlLocation, WSLANCARTAXASDIVERSAS_QNAME);
    }

    public WsLancarTaxasDiversas(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSLANCARTAXASDIVERSAS_QNAME, features);
    }

    public WsLancarTaxasDiversas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsLancarTaxasDiversas(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsLancarTaxasDiversasSoapPort
     */
    @WebEndpoint(name = "wsLancarTaxasDiversasSoapPort")
    public WsLancarTaxasDiversasSoapPort getWsLancarTaxasDiversasSoapPort() {
        return super.getPort(new QName("AGATA", "wsLancarTaxasDiversasSoapPort"), WsLancarTaxasDiversasSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsLancarTaxasDiversasSoapPort
     */
    @WebEndpoint(name = "wsLancarTaxasDiversasSoapPort")
    public WsLancarTaxasDiversasSoapPort getWsLancarTaxasDiversasSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("AGATA", "wsLancarTaxasDiversasSoapPort"), WsLancarTaxasDiversasSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSLANCARTAXASDIVERSAS_EXCEPTION!= null) {
            throw WSLANCARTAXASDIVERSAS_EXCEPTION;
        }
        return WSLANCARTAXASDIVERSAS_WSDL_LOCATION;
    }

}
